### ISSUE TITLE
Function missing return statement

### ISSUE THREAD

**Issue by LouDou** [hideakitai/MCP4728#1]
Hi,

First, thanks for the lib! It has helped me immensely get the DAC working with zero effort :)

However, there is just one issue reported by the compiler, which would be nice if it were fixed:

MCP4728.h: In member function 'uint8_t MCP4728::analogWrite(MCP4728::DAC_CH, uint16_t, bool)':
MCP4728.h:44:5: warning: no return statement in function returning non-void [-Wreturn-type]

The warning is pretty self-explanatory, literally just the `return` keyword is missing in the method implementation: https://github.com/hideakitai/MCP4728/blob/master/MCP4728.h#L43

Thanks,
Doug.

**Comment by hideakitai** [comment]
Hi, thank you for using and reporting issue!
I've fixed it in b2462e0e867b733ec51de99e3ff040c22e86780d, so check it out and let me know if you have another problem :) Thanks!
