### ISSUE TITLE
Undocumented clock speeds of the MCP4728

### ISSUE THREAD

**Issue by CaptClaude** [hideakitai/MCP4728#2]
Just a Comment and Thanks.
The library works brilliantly and there is a little trick you can make note of somewhere to save someone else the 4 hours it took for me to figure it out.  I'm sure that this would be obvious by inspection to even the most casual observer, but not me.  
Reason:  I needed to generate 60Hz sine waves and by default, this isn't satis-factually possible. Iterating through a 256-point array at 100kHz clock yields a 4.2Hz waveform.  By experimentation, I learned that this is limited by the clock rate of the i2c bus. 
With an ATmega328P (Nano clone), the highest clock rate supported by the i2c library (without assembly I assume) and the MCP4728 is 888kHz. The MCP itself supports a High-Speed mode of 3.4MHz but it is not obvious to me how to initialize the chip & processor & library to run that fast. 
```Wire.begin(100000L);``` sets 100kHz clock (default), ```400000L``` sets 400kHz and although undocumented anywhere I discovered that  ```800000L``` sets the clock to 800kHz and it works.
But we can squeeze a bit more out of it. ```twi.c``` (/Users/jm/Library/Arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src/utility/twi.c) contains the following code:
```
  // initialize twi prescaler and bit rate
  cbi(TWSR, TWPS0);
  cbi(TWSR, TWPS1);
  TWBR = ((F_CPU / TWI_FREQ) - 16) / 2;

  /* twi bit rate formula from atmega128 manual pg 204
  SCL Frequency = CPU Clock Frequency / (16 + (2 * TWBR))
  note: TWBR should be 10 or higher for master mode
  It is 72 for a 16mhz Wiring board with 100kHz TWI */
```
We know that this calculation can be overridden by specifying TWBR explicitly after
```Wire.begin()```.  A little pencil and paper work tells us that 100kHz clock is ```TWBR = 72```, 400kHz clock is ```TWBR=12``` and ```TWBR = 2``` yields 800kHz.  Since TWBR can't be negative, setting it to 1 gives us a clock of 888kHz.  With this I can generate three passable albeit ugly, 60Hz sine waves, 120deg offset (power system simulation).

**Comment by CaptClaude** [comment]
FYI: The library also works (unmodified) with the Adafruit M0 Trinket (Atmel ATSAMD21).  TWBR is not recognized and i2c bus clock speeds of up to 1.4MHz are possible.
e.g.: ```Wire.setClock(1400000L);```

**Comment by hideakitai** [comment]
I'm so sorry for late reply. Thank you for your information! I also discovered we can set clock by `setClock()`, thanks to your advice. Thank you so much again!
