### ISSUE TITLE
Device addressing: is it fixed?

### ISSUE THREAD

**Issue by lorenzos** [hideakitai/MCP4728#3]
The MCP4728 datasheet states that you can optionally set a three bit address on each device, to make it possible to use two or more MCP4728 on the same bus. But here the I2C device address is stored in a [constant private field](https://github.com/hideakitai/MCP4728/blob/master/MCP4728.h#L220), making it impossible to go beyond the single-chip default-address setup.

Why is that? Is it intended for some reason? The library that inspired your work is more cryptic, but it looks to [have this option](https://github.com/BenoitSchillings/mcp4728/blob/master/mcp4728.cpp#L34). Are there other differences in the functionalities of these two implementations?

Thanks!

**Comment by hideakitai** [comment]
You can [select IDs](https://github.com/hideakitai/MCP4728/blob/b2462e0e867b733ec51de99e3ff040c22e86780d/MCP4728.h#L126) and I2C address is changed depending on the ID. `I2C_ADDR` is NOT used to specify the address, but `addr_` is used. Please check the code again. Thanks!

**Comment by lorenzos** [comment]
Completely missed that, thanks!
