### ISSUE TITLE
Writing PowerDown modes to EEPROM?

### ISSUE THREAD

**Issue by m-elias** [hideakitai/MCP4728#5]
Is it possible to write power down modes for each channel to EEPROM? It appears to me that there is no function to change eep_[ch].pd but that is all I would need to do before calling analogWrite with b_eep = true?

**Comment by hideakitai** [comment]
Thanks, writing vref, power down mode, and gain to eeprom is missing now. I will add a flag if writing to reg or eep to `selectXxxx()` APIs.

**Comment by hideakitai** [comment]
`selectPowerDown(PWR_DOWN a, PWR_DOWN b, PWR_DOWN c, PWR_DOWN d)` can write power-down mode, but it does not affect EEPROM. To write to EEPROM, you need to use `Sequential Write` or `Single Write`. Please take a look at the specification section around 5.5 for more details.

https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/22187E.pdf
