### ISSUE TITLE
Arduino IDE delivers buggy version of this library

### ISSUE THREAD

**Issue by DuncanAtISIS** [hideakitai/MCP4728#6]
Hi, Arduino IDE library manager only knows about the buggy 2018 version of this library.  Thats the version tagged 0.1.0.
I presume that if you apply a tag to the latest (not buggy) commit, then that will be available by default through arduino IDE???

**Comment by hideakitai** [comment]
@DuncanAtISIS Thank you! I just remembered that I had to release the new version. Released v0.1.1

https://github.com/hideakitai/MCP4728/releases/tag/v0.1.1
